-- MySQL Script generated by MySQL Workbench
-- Tue May 11 18:24:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sinhan_road_trip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sinhan_road_trip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sinhan_road_trip` DEFAULT CHARACTER SET latin1 ;
USE `sinhan_road_trip` ;

-- -----------------------------------------------------
-- Table `sinhan_road_trip`.`day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinhan_road_trip`.`day` (
  `day_id` INT(11) NOT NULL AUTO_INCREMENT,
  `region_name` VARCHAR(45) NOT NULL,
  `hotel_id` INT(11) NOT NULL,
  `map_url` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`day_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sinhan_road_trip`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinhan_road_trip`.`hotel` (
  `hotel_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `map_url` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`hotel_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sinhan_road_trip`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinhan_road_trip`.`location` (
  `location_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image_url` VARCHAR(300) NOT NULL,
  `day_id` INT(11) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sinhan_road_trip`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinhan_road_trip`.`restaurant` (
  `restaurant_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `upvotes` INT(11) NOT NULL DEFAULT 0,
  `cuisine` VARCHAR(45) NOT NULL,
  `image_url` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`restaurant_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sinhan_road_trip`.`restaurant_has_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinhan_road_trip`.`restaurant_has_day` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT(11) NOT NULL,
  `day_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  INDEX `day_id_idx` (`day_id` ASC) VISIBLE,
  CONSTRAINT `day_id`
    FOREIGN KEY (`day_id`)
    REFERENCES `sinhan_road_trip`.`day` (`day_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `sinhan_road_trip`.`restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sinhan_road_trip`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinhan_road_trip`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sinhan_road_trip`.`user_has_favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinhan_road_trip`.`user_has_favorite` (
  `favorite_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `location_id` INT(11) NOT NULL,
  PRIMARY KEY (`favorite_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `location_id` (`location_id` ASC) VISIBLE,
  CONSTRAINT `location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `sinhan_road_trip`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `sinhan_road_trip`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sinhan_road_trip`.`user_has_upvote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinhan_road_trip`.`user_has_upvote` (
  `upvote_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `restaurant_id` INT(11) NOT NULL,
  PRIMARY KEY (`upvote_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
